config_INDI.cpp
Made more room in the INDI configuration dialog. 
Started with this as I could not see the full name of the selected camera.
Attached the dialog before and after:
=> Resizable and not to compressed INDI configuration

cam_qhy5.cpp
I'm owner of a Magzero Mz5-m camera (QHY5 camera for italian market brand) that doesn't work well with PHD2 on Raspberry (ubuntu mate 16.04 OS): in particular calibration and guiding procedures fail (i use a 9x50 finder as guidescope and all calibration and guiding settings are correctly set).
After many test I've found the reason: a bug in cam_qhy5.cpp file.
The bug is here:
`bool Camera_QHY5Class::ST4PulseGuideScope(int direction, int duration)
{
int result = -1;
int reg = 0;
int32_t dur[2] = { -1, -1};
duration /= 10;
if (duration >= 255) duration = 254; // Max guide pulse is 2.54s -- 255 keeps it on always`
with this settings calibration steps (and guiding corrections I suppose) are limited to 254 ms, a too short value for guiding expecially with short guidescopes (i.e. 9x50 finder …
=> Bug fixed as issue #565 - cam_qhy5.cpp file

cmake_modules/FindINDI.cmake, thirdparty/thirdparty.cmake
INDI 1.4 removed INDI Library (libindi.so) and so clients now need only to link with the static INDI client library (libindiclient.a) along with some dependencies (libnova, libz, libm). This pull request addresses this change and PHD2 can now compile with the latest INDI. It can also still compile on earlier versions of INDI.
=> Update PHD2 to compile with INDI 1.4

cameras/SXMacLib.c
@agalasso I've removed an old work-around where I was using a hard-coded interface number in the Mac build. This now uses the interface number from the config descriptor to match the Linux build.
=> #586: Remove hard-coded USB interface number from Mac build

CMakeLists.txt, thirdparty/thirdparty.cmake
I would like to package PHD2 for inclusion in Fedora and EPEL repositories, but in order to do so there must be a way to make it build using system libraries instead of bundled libraries.
This is a first patch to let user specify the use of system provided Cfitsio and libUSB. The appropriate options defaults to off, so they don't change anything to the previous build method. (the cfitsio part of the patch seems to change a lot, but I only added spaces to format lines for the new IF-ELSE statement I introduced - the code is untouched).
=> Allow the usage of system libs

event_server.cpp, socket_server.cpp
Use SO_REUSEADDR for servers so that event/socket server start does not fail on phd restart
=> Use SO_REUSEADDR for servers

staticpa_toolwin.cpp, staticpa_toolwin.h
Three groups of changes:
1) Enable saving Notes entered by user
2) Fix errors in instructions and make terminology consistect across instructions, labels and doco
3) On overlay use dotted lines and reduce intensity as overlay obscures the reference stars
=> Staticpa - add missing functionality and cosmetic fixes

cmake_modules/PHD2Packaging.cmake
Appdata standard has changed file location to /usr/share/metainfo.
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
=> Correct appdata file location

polardrift_toolwin.cpp
Restores guiding enablement to its original state even if PDA is closed unceremoniously. Also fixes the status bar to fit message and divide into discrete fields
=> Polardrift

cmake_modules/PHD2Packaging.cmake
Most current and upcoming DEB package based distributions
such as Ubuntu and Debian ship libnova in version 16.
Extend the package build dependency to encompass also libnova-0.16-0.
=> Extend DEB package build dependency of libnova

cam_touptek.cpp, cameras.h, thirdparty/thirdparty.cmake
I took the easy way out and changed S_OK to 0 on line 854 to get around a compiler error. You may want to define S_OK conditionally for Linux.
I changed from trigger mode to video mode as in trigger mode on both Win and Linux a 1s exposure led to a 1.6s sampling period. In video mode a 1s exposure is very close to a 1 sampling period.
In early testing of video mode I was getting an occasional long delay between frames but I have not been able to reproduce it recently. Could have been a USB issue.
While testing with a very artificial "star" I saw fairly large (0.5 pixel), high frequency deviation on the dec axis. What was weird is that when I turned on the target plot the mean position of the deviations switched to the other side of the axis. Ans when I switched it off again the mean …
=> Touptek on Linux

thirdparty/thirdparty.cmake
OpenSSag is not really "open" (its license file shows it's copyrighted), so it should not be linked if OPENSSOURCE_ONLY is set.
=> OpenSSag should be used only if not OPENSOURCE_ONLY

gear_simulator.cpp
Creating a new profile with just simulator
(Mount: none, Aux mount: none) causes a crash due to:
(gdb) bt
at /home/tstibor/dev/astronomy/phd2/gear_simulator.cpp:1010
at /home/tstibor/dev/astronomy/phd2/gear_simulator.cpp:1372
(camera=0x555556861400, duration=1000, img=..., captureOptions=3, subframe=...) at /home/tstibor/dev/astronomy/phd2/camera.cpp:1475
(gdb) p img
$4 = (usImage &) @0x555556620d70: {ImageData = 0x7fffec003510, Size = {x = 752, y = 580}, Subframe = {x = 0, y = 0, width = 0, height = 0}, NPixels = 436160, Min = 0,
Max = 0, FiltMin = 0, FiltMax = 0, ImgStartTime = {static ms_country = wxDateTime::Country_Unknown, static TIME_T_FACTOR = 1000, m_time = {m_ll = 1558298246075}},
ImgExpDur = 1000, ImgStackCnt = 1, BitsPerPixel = 16 '\020', Pedestal = 0, FrameNum = 0}
(gdb) p …
=> Fix crash due to nullptr access of pPointingsource in simulator

event_server.cpp
Advertise overlap support of the RPC api in the version message, so that clients can detect support (otherwise, clients using overlapped will break when used on older version of phd)
+ "just in case" ensure handle_cli_input is fully reentrant, without blocking anything
=> check reentrancy of handle_cli_input

event_server.cpp, event_server.h, phdconfig.cpp
This new event allows a client to keep in sync with any PHD configuration setting, using export_config_settings only when required.
I used a timer to ensure no burst of event are sent when PHD write multiple entries at once.
=> EventMonitoring: emit ConfigurationChange event

cam_indi.cpp, cam_indi.h, config_indi.cpp, config_indi.h
INDI exposures sometime fail because camera/driver is in wrong state (ex: already exposing, user abort from indi panel, invalid conf, ...)
On such condition, the current version fallbacks to stream mode with no way to switch back to exposure. Stream mode should be regarded as a fallback since it is only 8 bits and may include alteration of the signal (gamma correction in latest git, and probably jpeg mode on some cam)
The current PR adds an option to disable fallback stream usage. It defaults to false to not change anything on existing installation.
=> cam_indi: add an option to prevent fallback to streaming

cam_sxv.cpp, cameras.h, cameras/SXMacLib.c, cameras/SXMacLib.h, contributions/MPI_IS_gaussian_process/CMakeLists.txt, myframe.cpp, phd.h, scopes.h, serialport_posix.cpp, serialport_posix.h, stepguiders.h, thirdparty/thirdparty.cmake
Hello!
This PR contains changes required to make PHD2 compile on FreeBSD. The change highlights are that I've added definition checks for FreeBSD in a few places in the code, worked around a broken find_package for wxWidgets and excluded binary libraries that wouldn't link on FreeBSD.
I'm primarily interested in using Indi features together with PHD2 and I've upstreamed fixes to Indi to make it compile on FreeBSD again. At the moment, the only thing I've been able to properly test is webcam support via Indi using the V4L CCD driver that works on FreeBSD via webcamd. Attaching a webcam and getting images into PHD2 is working with the changes in this PR. Unfortunately, I am currently not able to test using my Celestron mount since it and I are geographically separate.
One question I have is …
=> FreeBSD 12.1: Add compilation support

cam_qhy.cpp
qhy cameras always appear to be 8 bits per pixel.  Use the value returned by GetQHYCCDChipInfo().
=> QHY: fix incorrectly-reported bits-per-pixel value for 16-bit cameras

darks_dialog.cpp, guider.cpp, image_math.cpp, image_math.h, myframe.cpp, usImage.cpp, usImage.h
The current dark subtraction algorithm works adequately when the light frames are are lighter than the dark frames, which is typically the case.  But when dark frames are lighter then the lights, the existing Pedestal calculation does not behave well since it is based on a the minimum per-pixel difference.  Bruce did some testing with user data frames and found that basing the pedestal value on the difference between the overall median ADU works much better.
In order to support this, we now calculate the median ADU value for each light frame, and for dark frames when they are loaded. When subframes are in use, the median is computed over the subframe ROI for both the dark and light frames.
=> Revise dark-subtraction algorithm to fix problem with star auto-selection due to invalid pedestal value

guider.h, myframe.cpp, myframe_events.cpp
Provide another way to de-select the guide star and restore full-frame display if sub-frames are being used.  The "place" in the UI where you selected the star is now the same place you go to de-select it, and there can be a tooltip to say how to do it.  The existing shift-click on the display area is fine but it is a hidden feature.
=> Add means to de-select star and restore full-frame image display

cam_ascom.cpp, cam_ascom.h, cam_indi.cpp, cam_indi.h, cam_zwo.cpp, camera.cpp, phd.h, scope_indi.cpp
Some ZWO ASI cameras break the assumption that the binned frame size is directly proportional to the un-binned frame.
Update the ZWO ASI native driver and the INDI camera client code to remove the assumption and use the actual binned camera frame to determine the binned frame size.
TODO: fix ASCOM cameras too
Fixes #878
=> ZWO / INDI / ASCOM cameras: do not assume binned frame size

guider_multistar.cpp
slight improvement to location of rendered secondary star circle position - multiply by scale factor _before_ truncation to int
this is consistent with how scale factor is used to render other objects
=> multistar: minor fix to secondary circle render location

star.cpp, star.h
Using `operator==` for a proximity check (and not strictly a C++ object equality check) breaks the abstraction of what operator== is expected to be.
This code is functionally equivalent to what is already there, but makes the intent a bit clearer by moving the proximity checking code out of operator== and into a new function `CloseToReference()`
=> multistar: minor code refactor to clarify intent of star proximity checker

thirdparty/VidCapture/Source/VidCapture/CVVidCaptureDSWin32.cpp
I had an issue with a [TSSSI][1] astro webcam (I know, probably extremely poor for guiding, but just starting 😄).
Since I already owned this camera (looks like a 1:1 Omegon Camera CCD clone) I wanted to give it a try.
So debugged down the issue to a simple zero-division, which was easily fixable.
Also seems this value is only used in the select drop-down, so seems rather safe.
Although it will now report the video modes as "0 fps", still better than crashing 🚀 
Thanks! Looking forward to actually try my new auto-guiding mount.
[1]: https://www.teleskop-express.de/shop/product_info.php/info/p1778_TS-Optics-Astro-CCD-Kamera---Mond---Planeten---1-25--Anschluss.html
=> Fix crash when wdm camera does not report AvgTimePerFrame

README-building-phd2-for-windows.txt
This README file has been obsolete for years. It just caused confusion for somebody -- getting rd of it.
=> remove obsolete README pointing to google code

cam_altair.cpp
The initial frame returned by the camera when looping first starts tends to be under-exposed, and this interferes with star auto-selection. We went through several rounds of SDK updates from the manufacturer attempting to address this problem in the camera SDK without success.
This code is a workaround for the problem - allow the user to specify a number of camera frames to discard each time looping exposures starts.
=> Altair cameras: add an option to discard initial camera frames

cam_ascom.cpp
When reconnecting an ASCOM camera, the camera object was using stale info (FullSize and m_roi) from the last time it was connected. This would result in failing to set a proper ROI before starting capture, and result in a capture error from some ASCOM drivers (including QHY).
The fix is to properly initialize FullSize and m_roi when connecting to the camera, as they are initialized the first time the camera is connected.
=> ASCOM cameras: fix an error from some cameras about invalid frame size after disconnecting and re-connecting the camera

cam_indi.cpp
The BIN value would otherwise reset to 1, dropping the dark library of the profile
Fix issue #910
=> Ignore the BIN value read from INDI driver on startup. Fix #910

CMakeLists.txt
The recently updated Touptek SDK has a more standard install name path, but the change broke our CMake build script which was looking for the old, unusual path.
=> OSX: fix touptek dylib path

debian/changelog
I have recompiled debian/changelog based on git commits, back to the first tagged version 2.5.0
This could be quite useful for packagers.
=> Debian changelog recompiled

build/make_release_dev, build/make_release_full
It is better to have an up-front check to detect when build machines are not available
rather than to have the scripts fail later on when they try to access the servers.
=> update release scripts to check build servers up front

phd.cpp
The call to ::exit() bypasses the ordinary sync of the config via the PHDConfig class destructor so
we need to flush it explicitly before calling ::exit()
Fixes #953
=> fix config not getting saved to disk on linux/mac with phd -l

guider.cpp, guider.h, guider_multistar.cpp
existing code uses HFD, newly added code uses Hfd; change new code to use the
prior convention. Also,
- wrap long lines
- fix an unused local variable
=> use uniform captialization for HFD

cam_svb.cpp
When changing ROI or binning, PHD2 was calling SVBStopVideoCapture which would sometimes hang. Removing the call makes capturing more stable, and ROI and binning change continues to work as expected without the call.
=> SVB cameras: improved stability when changing ROI or binning

debian/control
=> update buildeps for newer package name

cmake_modules/PHD2Packaging.cmake
Additional fix to #975 to allow cmake to generate a debian package for Ubuntu 20.04.
=> Fix cmake debian dependencies.

cam_zwo.cpp
This avoids non-deterministic behaviour if white-balance
has been adjusted from another application
=> Set colour balance to unity on connection

usImage.cpp, usImage.h
remove unused method BinnedCopyToImage
also, some cosmetic changes to make code style more uniform;
also, use operator delete[] matching operator new[]
=> dead code removal

cam_svb.cpp
SVBPulseGuide returns immediately after being called.    It does not wait for the guide pulse to complete.    A delay is necessary to avoid starting an exposure while the mount is moving.    It is also desirable to avoid calling SVBPulseGuide while a pulse is active.
I have verified this is the designed behavior of SVBPulseGuide with SVBony technical support.
=> SVB Cameras: make ST4 Pulse guide commands synchronous

thirdparty/thirdparty.cmake
This is required because PHD2 is statically linked with this library. 
Installing in  /usr/lib/phd2 make it work the same way as the Toupcam SDK.
$ ldd /usr/bin/phd2.bin
...
libtoupcam.so => /usr/lib/phd2/libtoupcam.so (0x00007fc347a00000)
libSVBCameraSDK.so => /usr/lib/phd2/libSVBCameraSDK.so (0x00007fc347200000)
...
Fix #1010
=> On Linux, install the SVBony SDK libSVBCameraSDK.so to /usr/lib/phd2

build/make_release_dev, build/make_release_full
update the build scripts to accommodate our new external web host
generating and deploying the static site now needs to come last to ensure that all updates to the the local staging location get propagated to the production static site
=> build scripts: changes to support remote hosted static site

camera.cpp, guide_algorithm_gaussian_process.cpp, help/Supplemental_Info.htm
Continue to see situations where mis-behaved mounts can create unhandled exceptions in underlying PPEC libraries - these often cause crashes.  Try/catch is a start on the problem but Windows structured exceptions won't be caught.  Other changes are pretty trivial.
=> Dev3 changes

build/make_release_dev, build/make_release_full
Tag the release as soon as the builds succeed, prior to publishing the ChangeLogs to Wordpress. This makes it slightly easier to resume processing if publishing the ChangeLog to Wordpress fails.
=> build scripts: tag release sooner

myframe.cpp
The ZWO software often scrambles the camera connections and users don't understand the current PHD2 alerts about sensor geometry and dark libraries.
=> Improve alert messages for camera geometry mismatches

cam_indi.cpp, config_indi.cpp, config_indi.h, indi_gui.cpp, indi_gui.h, phdindiclient.cpp, phdindiclient.h, scope_indi.cpp, stepguider_sbigao_indi.cpp, stepguider_sxao_indi.cpp
For [INDI Core](https://github.com/indilib/indi) 1.9.9 and 2.0.0, the `serverConnected` virtual function executes too early.
Implementing this function to wait for device information loses its purpose as it blocks requests for device information from being sent.
The detected problem is described in [Mount connection times out with INDI 2.0 #1036](https://github.com/OpenPHDGuiding/phd2/issues/1036), and all other related topics.
**This pull request should be compatible with previous and future versions of INDI Core.**
I'm adding your great PHD2 project to my list of tests and support for heavy upgrades to the INDI Core library.
If you allow me, I will propose implementation simplifications as pull requests as far as possible to reduce the amount of code and simplify the use of the INDI …
=> Fix serverConnected call too early for INDI Core 1.9.9/2.0.0

phdindiclient.h
Fixed compilation error for INDI versions below 1.9.9. Detected bug described in the thread: https://github.com/OpenPHDGuiding/phd2/issues/1038
=> Build Fix - Use `override` for connectServer since 1.9.9 indi.

calibration_assistant.cpp
somehow the code actually compiles on Windows without this fix !?
Fixes #1047
=> fix compile error in calibration_assistant.cpp

event_server.cpp
I'm working on implementing a client library for phd2 in rust, and I've come across an issue in the rpc response to `get_star_image`; the base64 encoded string in the `pixels` field is invalid because it has a null byte at the end.  You can see it here, in the result of calling `get_star_image` against phd2 in simulator mode:
```json
"{\"jsonrpc\":\"2.0\",\"result\":{\"frame\":5,\"width\":15,\"height\":15,\"star_pos\":[7.21,7.03],\"pixels\":\"siEUHcQXJCwWIu4sQiAiGjohpCrQH+YpIiA2KWguMB64Hu4rBC7sJ6YizCZAIWobmiNOJNQbdi3sHlgpsCF4JfwnVihmGYop1CQ4K7QlGBi4GyIqDC5MHmQd9B3cJeAazCv2LYofDB5CJ2oifB8uJHYl3iFgIbgcthrcJ+gZgi6QJ+IeMB30GHAtmCXoLDIcui7YIcQd+i34KFYbniQyLpghAjfXM/4pQxq4KGgkXBqgIEAh2ixsHawXkitOIvYxzd3/////ZVTzGfQgThqmIwIa2iBeLrYoihncJCg3////////Bpi+KwAZghgwJvoguiU+KVgbGBmeKeIunev/////CUTEIxwnv …
```
=> Remove zero byte from end of base64 encoded star image.

guider.cpp, guider.h, guider_multistar.cpp, guider_multistar.h, star.cpp, star.h
Implementation of Max-HFD to handle clumps of sensor noise, internal reflections, unwanted comet heads and other sources of false star detection. Default value will not change historical behavior of star selection.
=> Group Min/Max HFD controls in UI; clean-up for Max-HFD implementation

image_math.h, scope_indi.cpp, scope_manual_pointing.cpp
This is an alternative to #1095 but provides a computed LST value rather than just returning an error.
The LST computation was already present in scope_manual_pointing.cpp, but has been moved to make it accessible to scope_indi.cpp as well.
=> Compute LST in PHD2 if INDI driver does not provide it and libnova is not available

phd2.iss.in, thirdparty/thirdparty.cmake
Copy the files to the build directoy so the dll's that need them find them there.
=> Do not rely on the bundled VC runtime files being present on the system.

CMakeLists.txt, contributions/MPI_IS_gaussian_process/CMakeLists.txt, thirdparty/thirdparty.cmake
The Windows build was always linking against the vcpkg release libraries. Now we link against the debug libs in debug builds, and the release libs in release builds.
=> Windows build: link with VCPKG debug or release libraries

phd.cpp
```
$ ./phd2.bin --help
Usage: phd2 [-?] [-i <num>] [-l <str>] [-R] [-s <str>] [-v]
-?, --help                	display this help and exit
-i, --instanceNumber=<num>	sets the PHD2 instance number (default = 1)
-l, --load=<str>          	load settings from file and exit
-R, --Reset               	Reset all PHD2 settings to default values
-s, --save=<str>          	save settings to file and exit
-v, --version             	print the program version and exit
$ ./phd2.bin --version
2.6.12
```
=> add a command-line option to print the program version

scope_indi.cpp
#1129 accidentally reverted method rename from GetDeclination() to GetDeclinationRadians() done in #1045  causing declination to be reported as unknown. Renaming the method back to GetDeclinationRadians() fixes it. Fixes issue #1134 .
=> Fix accidental revert of renaming GetDeclinationRadians() 

thirdparty/thirdparty.cmake
The commit for #1144 bumped the cmake minimum version to 3.24 since we now use the FetchContent module.  This had a side-effect of changing policy CMP0126 https://cmake.org/cmake/help/latest/policy/CMP0126.html which caused the wxWidgets find_package call to fail as the wxWidgets_CONFIGURATION variable was being set as a normal (non-cache) valriable.
=> fix cmake error on Windows

build/publish_osx
This should identify unwanted Mac dylib dependencies at build time, before they get deployed into a release.
=> Mac build: add a dylib dependency sanity check

CMakeLists.txt, contributions/MPI_IS_gaussian_process/CMakeLists.txt, thirdparty/thirdparty.cmake
Testing:
- `cmake -DUSE_SYSTEM_GTEST=ON -DUSE_SYSTEM_LIBINDI=ON -DUSE_SYSTEM_EIGEN3=ON -DUSE_SYSTEM_LIBUSB=ON  ..`
- `make`
- `make -C tmp_gaussian_process test`
=> reinstate USE_SYSTEM_GTEST build option

cam_indi.cpp
Change the error message when receiving a FITS file from INDI with NAXIS=3
Please comment if the new message is not clear enough.
Fix #1157
=> Better error message for RGB FITS file from INDI

star_profile.cpp
A set of commits fixing few scaling factors used to prevent HFD metrics clipping at the window edges or by other window elements, enhancing accuracy of displayed star centroid, clearing previously uninitialized state variables - all resulting in a cleaner UI and predictable behavior.
=> Star profile layout tweaks

star_profile.cpp
As a follow-up commit to Star Profile tweaks, this is designed to put an upper limit on large font size and prevent making it too big.
=> Star Profile Window: limit size of the large font.

statswindow.cpp
Prevent resizing of rows and columns in stats grids to protect against inadvertent change of cell size by the user.
=> Prevent resizing of rows and columns in stats window

cam_indi.cpp, scope_indi.cpp, stepguider_sbigao_indi.cpp, stepguider_sxao_indi.cpp, thirdparty/thirdparty.cmake
This push attempts to fix "Problem with connection status when connecting Indi devices in v2.6.13dev1 [#1174 ]"
This new code monitors the INDI device's 'Connected' property and waits for it to be 'true' before releasing the Connect method back to the UI. I tried to move the wait loop into the RunInBG template so users are able to cancel.
It's been tested with an aarch64 bit build using the Indi scope and camera simulators. I verified that
* Camera simulator and mount simulator are connecting
* Both devices show as connected
* The Dark frame library is assigned successfully
* No alerts with respect to camera connectivity and bad-pixel maps or dark libraries 
* "Connect All" button connects both devices and then closes gear selection dialog.
Concerns or advise is welcome. I am not overly …
=> Update INDI device's Connect method to wait for 'Connected' property

usImage.cpp
Using delete instead of delete[] for memory allocated with new[] is a common mistake that can lead to undefined behavior. The consequences of this mismatch between allocation and deallocation mechanisms can vary depending on the compiler, the runtime environment, and the specifics of the program.
=> Histogram builder: fix incorrect delete operator

CMakeLists.txt, cameras.h, debian/control
With the change for OpenCV4 the OpenCV camera now work fine on Linux.
Tested with a laptop webcam.
This is interesting to add because this can support other devices than the V4L2 INDI driver. 
The change is trivial, but please let me know if there is another/better location for "find_package".
I not added conditional switch because OpenCV will anyway be required by the new planetary module.
=> Add OpenCV camera with Linux, the new code for OpenCV4 work fine

cam_touptek.cpp, image_math.h
move some binning methods out of cam_touptek.cpp into image_math.h so the methods can be used by another camera in a forthcoming PR
no functional changes
=> minor refactor for code reuse

advanced_dialog.cpp, advanced_dialog.h, camera.cpp, gear_dialog.cpp, mount.cpp, myframe.cpp, myframe.h
This revises earlier code that reacted to image scale changes in an existing profile.  This revision takes a more straightforward approach that mimics the code in the new-profile-wiz to create from-scratch settings for calibration step-size and MinMoves.  It forces a fresh calibration after the changes are made but doesn't do the broad-brush guide algorithm resets that were done in the original code.  The original code was too vulnerable to situations where user-controlled settings were already out-of-whack.
=> Rework of image-scale change handling

debian/control, debian/rules, thirdparty/thirdparty.cmake
With the recent addition of OGMA camera it is no more possible to build the Ubuntu PPA package.
This is because it is not possible to reach Github from the Ubuntu build server to download the library.
Even with -DOPENSOURCE_ONLY=1 it still try to fetch the library, making the build to failed.
This change just prevent the fetch when OPENSOURCE_ONLY=1.
=> Do not try to fetch the Ogma camera library whith OPENSOURCE_ONLY

statswindow.cpp, target.cpp
I'll add later a few screenshots to show what was fixed.
=> Target window: tweak positions of graphical elements to avoid overlap (part4 for planetary guiding)

build/make-release
keep the Debian changelog up-to-date by always prepending the ChangeLog text ([dpkg-changelog](https://manpages.debian.org/testing/dpkg-dev/deb-changelog.5.en.html) formatted) when building a release
=> build script -- automatically update the debian changelog

calreview_dialog.h, calstep_dialog.cpp, cam_OSPL130.cpp, cam_ascom.cpp, camcal_import_dialog.cpp, cameras/vcap_v4l.h, cameras/vcap_vfw.h, cameras/vcapwin.h, darks_dialog.cpp, logger.cpp, myframe.cpp
code cleanup: use angle brackets for wxwidgets includes
Use `#include <wx/...` consistently, not `#include "wx/.."
=> code cleanup: use angle brackets for wxwidgets includes

src/event_server.cpp, src/event_server.h
event server: fix possible problems when client sends multiple requests
The `connect` command can cause the event loop to run and for the event server to process additional buffered client commands.  As the JSON parser instance is reused for all client commands, the parser's state will reflect the most recent client command and may lose the state of the unfinished connect command.
The fix is to not reuse the JsonParser instance -- instantiate a dedicated parser for each client command.
Testing:
- manually exercised the event server by issuing commands with an event server client
- checked the runtime overhead of instantiating the JsonParser instance per request (negligible, < 100 ns)
=> event server: fix possible problems when client sends multiple requests

cmake_modules/PHD2BuildDoc.cmake
* PR #1231:
`andy/build-locales-src-directory` ➔ `andy/remove-unused-file`
* PR #1230:
`andy/remove-unused-file` ➔ `master`
run xgettext in the src directory
update the xgettext command to find the source files since we moved them to src/
Fixes #1229
=> run xgettext in the src directory

cmake_modules/PHD2Packaging.cmake
Some icons and desktop files was references from the src dir but they are located in other places.
=> Corrected path for installed files

src/event_server.cpp
This adds a new JSON-RPC API method, `set_cooler_state`, which takes a single boolean argument to turn the cooler on or off if the connected camera is equipped with one.
Turning the cooler on:
```json
{"method":"set_cooler_state", "params": [ true ], "id":1}
```
Turning it off:
```json
{"method":"set_cooler_state", "params": [ false ], "id":1}
```
This will permit full automated setup of the camera from an API client. Currently, the cooler must be manually turned on via the Advanced Settings > Camera window. This complements the existing `get_cooler_status` method.
=> Add cooler control API method

src/camera.cpp, src/guider_multistar.cpp, src/star.cpp
A user was recently using subframes with multistar guiding enabled.  This created bogus exception messages in the debug log and a rather misleading display.  This commit should resolve those problems.  I didn't want to take the simplest route of just disabling multistar guiding when subframes were enabled because that would probably confuse users.  With this commit, users can enable/disable sub-frames while guiding is active and the behavior should be what is expected.
=> Multi star subframe

src/cam_qhy.cpp
This is the final installment of my QHY native driver project. This has gone through some intensive testing with some users so it lagged a little.
The two main themes of this are:
1. Detecting if 16bit mode is even possible and reacting appropriately. This is needed for the original QHY5II (non-L) camera, apparently, which ran in 8bit mode only
2. Always set the exposure duration before initiation of camera exposure. This resets the camera's internal rolling loop of sensor readouts and resets so that the resulting frame is aligned as close as possible to the time which PHD2 initiates the exposure and when it is available. There has been some talk in the past about this issue with QHY cameras and how it can negatively affect the guiding performance of some mounts. There's no harm in making …
=> Final QHY improvements

contributions/MPI_IS_gaussian_process/src/gaussian_process_guider.cpp, contributions/MPI_IS_gaussian_process/src/gaussian_process_guider.h, src/mount.cpp
Add a Write method to GPDebug::Log for logging an already formatted C-style string. This is a workaround for GPDebug::Log not being able to handle a format string with %s.
=> Workaround for GPDebug::Log not working with format %s

contributions/MPI_IS_gaussian_process/src/gaussian_process_guider.cpp, contributions/MPI_IS_gaussian_process/src/gaussian_process_guider.h, contributions/MPI_IS_gaussian_process/tests/gaussian_process/gp_guider_test.cpp, src/guide_algorithm_gaussian_process.cpp, src/guide_algorithm_gaussian_process.h
GP guider needs accurate time interval measurements, and is not interested in the wall clock.  std::chrono::steady_clock is a better choice than system_clock.
Testing:
- gp guider unit tests pass
=> Predictive PEC: use the monotonic clock rather than the system wall clock

CMakeLists.txt, build/build-win, run_cmake-osx, run_cmake.bat, thirdparty/thirdparty.cmake
- use WXWIN environment variable directly so callers do not need to set wxWdgets_PREFIX_DIRECTORY when invoking cmake
- Windows: use the Visual Studio 17 generator by default (so callers do not need to specify it)
- Remove INDI as an explicit dependency of the phd2 executable CMake target. This will speed up the incremental edit-compile-test cycle a little bit, but developers will have to build INDI once before building the phd2 target specifically. In Visual Studio this means building the whole solution once before building the phd2 project.
=> build system tweaks

cmake_modules/PHD2Packaging.cmake, phd2.sh, phd2.sh.in
Allows `make install` run with a CMAKE_INSTALL_PREFIX other than the default (`/usr`) to generate a phd2.sh with the matching install prefix.
=> Linux: update phd2.sh to use CMAKE_INSTALL_PREFIX

src/cam_altair.cpp, src/cam_atik16.cpp, src/cam_playerone.cpp, src/cam_qguide.cpp, src/cam_qguide.h, src/cam_qhy5.cpp, src/cam_qhy5.h, src/cam_sspiag.cpp, src/cam_sspiag.h, src/cam_zwo.cpp
A bunch of the cameras implement ClearGuidePort which is not needed and has no callers, but it keeps getting propagated when new cameras a copy-pasted from older ones.
=> Code cleanup - dead code removal (ClearGuidePort)

src/cam_playerone.cpp
Attempting to select or connect to Player One cameras on Linux has crashed the program since #1278.  Renaming the `POACamera` class to something else like `PlayerOneCamera` fixes the issue, since the Player One SDK may already uses the name.
Tested on x64, Arm64 Debian 12 and Windows 11.
=> Fix crash with Player One cameras on Linux

contributions/MPI_IS_gaussian_process/tests/gaussian_process/gp_guider_test.cpp
While it work fine with previous version of Ubuntu,  the last version 24.10 fail to build with this error:
```
/<<PKGBUILDDIR>>/contributions/MPI_IS_gaussian_process/tests/gaussian_process/gp_guider_test.cpp:555:25: error: ‘setw’ is not a member of ‘std’
555 |         outfile << std::setw(8) << GPG->GetGPHyperparameters()[PKPeriodLength] << "\n";
|                         ^~~~
/<<PKGBUILDDIR>>/contributions/MPI_IS_gaussian_process/tests/gaussian_process/gp_guider_test.cpp:120:1: note: ‘std::setw’ is defined in header ‘<iomanip>’; this is probably fixable by adding ‘#include <iomanip>’
119 | #include "guide_performance_tools.h"
+++ |+#include <iomanip>
```
Applying the suggest change work, the package for 24.10 is now in the PPA and I tested it work without problem.
Probably "iomanip" was …
=> Fix build with Ubuntu 24.10

thirdparty/thirdparty.cmake
`GIT_SHALLOW` is incomaptible with `GIT_TAG` being a SHA for FetchContent_Declare()
Fixes #1290
=> Fix build error due to invalid CMake function parameter

src/guider.cpp
This fixes a latent problem with initialization of the guider window size.  Two of the passed parameters in the constructor - xsize and ysize - are ignored in the original code.
=> Allow client to specify starting window size in Guider

src/cam_ogma.cpp, src/cam_touptek.cpp
The `GetCoolerStatus()` function for ToupTek and OGMA cameras did not set the `temperature` pointer with the cooler temperature readout, causing PHD2 to display garbage of an uninitialized variable. This PR fixes that so that the temperature is fetched and thus properly displayed. Although also ToupTek-based, the Malincam and Altair drivers leave these functions unimplemented and I felt that adding them would be outside the scope of this PR, plus I don't have any such devices to test with to ensure proper function. I tested this fix with a ToupTek ATR585M.
Before:
After:
=> Fix ToupTek/OGMA sensor temperature

src/star.cpp
Modifies a PR done in dev5 that auto-adjusted saturation-adu level using the bits-per-pixel property of the driver.  This didn't work correctly for drivers that don't scale 10, 12, or 14-bit ADC output to the 16-bit data range.
=> Remove auto-adjustment of Saturation-ADU

src/calibration_assistant.cpp
Don't do repeated backlash clearing slews on high-precision encoder mounts, only on the initial slew.  Avoid complaining about a low guide speed when it's slightly below 0.5x sidereal because of a rounding error.  This is a problem with SB mounts because the driver author used seconds instead of sidereal seconds.
=> Calibration Assistant improvements for encoder mounts and SB mounts

src/usImage.cpp
log a message in the debug log when saving an image fails
=> log a message in the debug log when saving an image fails

src/event_server.cpp, src/event_server.h, src/myframe.cpp, src/myframe.h, src/myframe_events.cpp
event server: capture_single_frame enhancements
Updated the capture_single_frame server method to allow more flexibility.
- allow the caller to optionally specify the exposure duration, binning, gain, and ROI
- allow the caller to optionally request that the image be automatically saved when the
exposure completes.  The caller can provide a path name for the output file
(the file must not already exist); when omitted PHD2 will choose a unique
output filename.
- on completion of the frame, PHD2 sends a SingleFrameComplete notification event.
The event will be sent on both success and failure.
=> event server: capture_single_frame enhancements

src/cam_altair.cpp
minor cleanup to altair camera code
- rename some variables
- use wxSize::Scale
=> minor cleanup to altair camera code

src/camera.cpp, src/camera.h, src/gear_dialog.cpp, src/profile_wizard.cpp
Minor refactor - add a camera Connect wrapper method
Add a wrapper method to call Camera::Connect.  This will allow us to
put code common to all camera subclass Connect methods in ConectCamera
rather than repeating it in all camera subclasses' Connect methods.
=> Minor refactor - add a camera Connect wrapper method
