OpenPHDGuiding/phd2

cam_SXV.cpp, cameras/SXMacLib.c, cameras/SXMacLib.h
Adopt timeout from Camera settings, report read pixels errors to caller and disconnect camera, tidy up code to get camera params
=> SXMacLib: Better timeout and disconnect support

CMakeLists.txt
Fix locales and help installation under linux and add Italian translation to the available languages.
=> Fix linux locales

cmake_modules/PHD2Packaging.cmake, phd2.appdata.xml
Add appdata file in linux installations.
See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
=> Add appdata file

cam_SBIG.cpp, cam_SBIG.h, cameras.h, thirdparty/thirdparty.cmake
o Add color support for cam_SBIG
o Latest stable indilib still requires nova
o Use a system installed level of SBIG universal drivers
=> Open phd guiding base

staticpa_toolwin.cpp, staticpa_toolwin.h
Enabled scrollbar on instructions with wxHtmlWindow
Fix bug leading to a negative radius
Sorted and labelled reference stars, label on overlay
Added debug statements to CalcRotationCentre where they are most needed
Slight reorder of code in constructor to a more logical sequence
=> Staticpa - bug fix, useability and debugging enhancements

staticpa_toolwin.cpp
Fix two bugs:
Inverted display due to pier side 
helper display rotating at 4x rate indicated by hour angle
=> Staticpa bug fixes

myframe.cpp, polardrift_toolwin.cpp, polardrift_toolwin.h
Prefix member variables with "m_"
Tag text for translation
Tooltips for the 3 PA tools
=> PolarDrift code cleanup

staticpa_toolwin.cpp, staticpa_toolwin.h
Code cleanup to standardise on "m_" prefix and tag for text translation.
Use hypot function where appropriate
Reduce size of SPA window by toggling between instructions and star map.
=> Staticpa - code cleanup

aui_controls.cpp, configdialog.cpp, darks_dialog.cpp, eegg.cpp, event_server.cpp, gear_dialog.cpp, logger.cpp, myframe.cpp, myframe_events.cpp, serialport_posix.cpp, star.cpp
These changes fix some compiler warnings, mostly comparisons between signed and unsigned.
In eegg.cpp file it seems that there's an if statement wrongly bracketed (or is the indentation wrong?).
=> Fix some compiler warnings

thirdparty/thirdparty.cmake
Applies patch to fix https://github.com/OpenPHDGuiding/phd2/issues/650 on ARM
=> Force bundled ZWO lib use

polardrift_toolwin.cpp
When PolarDrift tool is stopped restore guiding enablement to the state prior to PolarDrift. Also some fixes to debug messages and corrections to inline comments
=> Polardrift restore guiding status

calstep_dialog.cpp, calstep_dialog.h, profile_wizard.cpp, scope.cpp, scope.h, stepguider_sxao_indi.h
This PR removes the hard coded calibration distance and allows for the distance to be configurable. This was explored as part of troubleshooting a Mach1 (https://www.cloudynights.com/topic/622947-mach1-dec-oscillations-our-experience/?view=getnewpost) and also provides users more flexibility in configuring calibration to better match their particular imaging setup. Stock calibration worked great at 952mm focal length, but at 2800mm it was inadequate given my image scale.
**New Features**
- Removed the hard coded limit (25 px or 5% of height of image, whichever is smaller)
- Added UI in Calibration Step Calculator
- Added UI in the Advanced Setup -> Guiding tab
- Added calibration distance to log
I have tested it on a Mach1 with a C11 EdgeHD with an OAG at a pixel scale of 0.35 arc-sec/px …
=> Configurable Calibration Distance

CMakeLists.txt, stepguider.cpp, stepguider_sbigao_indi.cpp, stepguider_sbigao_indi.h, stepguider_sxao.h, stepguiders.h
This adds support for INDI SBIG AO driver. It was tested with SBIG AO-8
=> Adding INDI SBIG AO driver support

polardrift_toolwin.cpp
This fixes issue https://github.com/OpenPHDGuiding/phd2/issues/773
=> Allow to resize polardrift window for better reading status bar msg

cam_indi.cpp
The bug is rapidly visible when choosing a low exposure duration with the indi_ccd_simulator driver.
On my setup, exposure will timeout within one minute.
I found that the driver was starting an exposure while the exposure prop is still busy. This PR adds a wait loop on that condition before starting the exposure.
=> INDI camera hang fix: do not start exposure while previous is still busy

guider.cpp, guider.h, guider_onestar.cpp, guider_onestar.h, star.cpp
adds an option for downsampling the auto-select camera frame
=> star auto-selection: add option for downsampling the camera frame

log_uploader.cpp
By default, hide logs with no guiding. Checking the box shows the empty logs -- needed for the less common cases where somebody just has a debug log they want to upload with no guide log.
=> log uploader: do not display empty logs by default

locale/pl_PL/messages.po
I added missing translations and fixed incorrect translations.
=> Updated Polish translation

about_dialog.cpp
add Marcel to the Help > About window
=> about_dialog: add Marcel

event_server.cpp, event_server.h, guide_algorithm_gaussian_process.cpp, guider.cpp, guider.h, guider_multistar.cpp, guider_multistar.h, guiding_assistant.cpp, guidinglog.cpp, mount.cpp, point.h, star.cpp, star.h, star_profile.cpp
add the star info (mass, HFD, SNR) to the event server LoopingExposures event
Fixes #914
=> event server: add star info to the LoopingExposures event

cam_svb.cpp
should also cover other future Svbony mono cameras
fixes #941
keeping as a Draft until we get confirmation the the changes work
=> Svbony cameras: add support for SV305M PRO camera

debian/changelog
=> Updating debian packaging files

usImage.cpp
Using a LUT give a roughly x20 speed improvement to the CopyToImage function. 
I did a micro benchmark and it is clearly in favor of LUT:
On recent x86 - 2100% improvment:
current float arithmetic: rate: 86.721807 Mb/s
lut : rate: 1814.676194 Mb/s
On a rpi - 1800% improvment:
current float arithmetic - rate: 0.490497 Mb/s
lut : rate: 8.791209 Mb/s
Overall, on my system, this MR lowers global CPU usage when looping by ~30%
=> Use LUT for gamma computation

cam_indi.cpp
This MR allow faster INDI blob transfer when available (through local connections)
The shipped indilibrary doesn't support it, but latest build from master will.
The speed-up is noticeable, ~60% better just for looping in PHD
The MR also replace polling by condition notification
Reference: https://github.com/indilib/indi/pull/1668
=> [INDI] Use shared mem if available

usImage.cpp
Building an histogram is efficient to seek the median since the number of ADU value is limited. 
On my testing, I got another 30% cpu amelioration when looping against previous LUT optimized.
=> Use histogram for median computation

profile_wizard.cpp
The higher-end Planewave systems come with rotators and we're seeing an influx of these systems - so we need to handle this in the new-profile-wizard.  I didn't want to waste a bunch of time creating a new icon but someone can do that down the road.
=> Add rotator selection to new-profile-wizard

build/locales_update_win.sh
the script was present on my windows system but never got added to the repo
=> add missing build script

calibration_assistant.cpp
=> fix compile error on Linux/Mac

star_profile.cpp
Response to compile-time issue noted by Patrick:
https://github.com/OpenPHDGuiding/phd2/issues/1083
=> Fix compile error on Linux

profile_wizard.cpp
Initial implementation for profile-wiz to set saturation ADU based on cam bit depth if known.  I'm still seeing many instances of 16-bit drivers being used with a saturation value of 255.  This doesn't "fix" existing profiles.
=> Add profile-wiz ability to set saturation ADU based on camera bit depth

comdispatch.h, scope_ascom.cpp, scope_ascom.h
ScopeASCOM::SetupDialog change to address #1106.
=> ScopeASCOM::SetupDialog should not unconditionally destroy COM scope instance

cameras/toupcam.h
fixed issues of new G3M series models and SkyEye Series models
=> update Touptek lib to version 54.23926.20231119

cameras/toupcam.h
This reverts commit b3183782fd633c97d2b02aba85a441d7a476f4d8.
=> Revert "update Touptek lib to version 54.23926.20231119 (#1120)"

cam_indi.cpp, config_indi.h, indi_gui.h, scope_indi.cpp, stepguider_sbigao_indi.cpp, stepguider_sxao_indi.cpp, thirdparty/thirdparty.cmake
This fixes the issue on Windows and PHD2 runs and connect to INDI server just fine. The problem is that add_external project does not appear to be working as intended on Linux.
=> Fix PHD2 compile on Windows

camera.cpp
Reduce nesting of sizers in AD camera tab and do not rely on "Has" properties to create cam property controls.
Fixes #1125
=> Fixes for camera tab of Advanced Settings dialog

build/build_help_pdf.sh
add required arguments to wkhtmltopdf
=> fix error generating help file PDF on Linux

log_uploader.cpp
tested by uploading a log file and confirming the upload speed was logged as expected
=> Fix warning when compiling against recent libcurl

locale/cs_CZ/messages.po
updated Czech translation from Stanislav
=> updated cz translation

profile_wizard.cpp
Simple fix for a crash in profile wizard
=> Fix crash due to inaccessible pointer

guider.cpp
Includes speed optimization with insignificant impact on image quality when performing rescaling of captured camera image on the main window.
=> Minor speed optimizations

CMakeLists.txt, config_indi.cpp, config_indi.h, myframe.cpp, myframe.h, rotator.cpp, rotator_indi.cpp, rotator_indi.h, rotators.h
Good day,
First of all, thank you for your great work.
I took the liberty of adding support for INDI rotators. Large portions of this code have been adapted from the INDI scope and camera implementation.
I am aware of #1089 but am not sure how to proceed with regards to it. In case this PR is useful and being considered for merge, maybe some comments from the maintainers could help. Of course I'd be very happy with someone else adapting it to INDI 2, in line with the changes by Jasem.
Would address #1041 
Thank you,
Philipp
=> Add INDI Rotator support

guider.cpp
Fix incorrect calculation of average distances for RA
=> UpdateCurrentDistance: use distanceRA for calculating RA averages

cam_opencv.cpp, cam_opencv.h, phd2.iss.in, thirdparty/thirdparty.cmake
Testing:
- built installer, installed and tested opencv camera on Windows
=> opencv - update to version 4

CMakeLists.txt, cam_ogma.cpp, cam_ogma.h, camera.cpp, cameras.h, phd2.iss.in, thirdparty/thirdparty.cmake
The OGMA camera SDK is a clone of the Touptek SDK with symbols renamed.
Tested with a sample OGMA camera on Windows.
=> OGMA Camera support added

gear_simulator.cpp, mount.cpp, star.cpp
Fixed a few spelling errors in comments
=> Spelling fixups (part2 for planetary guiding)

src/cam_qhy.cpp, src/cam_qhy.h
This PR addresses the points raised in #1245 
The new options window presents thusly:
Tooltips are provided for each option that explains its purpose and any model-specific relevancy.
=> QHY driver improvements

thirdparty/thirdparty.cmake
minor speed improvement when starting from a clean build directory
=> minor CMake cleanup - use shallow option for git repo pulls

.github/workflows/clang-format-check.yml, contributions/MPI_IS_gaussian_process/src/covariance_functions.cpp, contributions/MPI_IS_gaussian_process/src/covariance_functions.h, contributions/MPI_IS_gaussian_process/src/gaussian_process.cpp, contributions/MPI_IS_gaussian_process/src/gaussian_process.h, contributions/MPI_IS_gaussian_process/src/gaussian_process_guider.h, contributions/MPI_IS_gaussian_process/tests/gaussian_process/evaluate_performance.cpp, contributions/MPI_IS_gaussian_process/tests/gaussian_process/gaussian_process_test.cpp, contributions/MPI_IS_gaussian_process/tests/gaussian_process/gp_guider_test.cpp, contributions/MPI_IS_gaussian_process/tests/gaussian_process/guide_performance_test.cpp, contributions/MPI_IS_gaussian_process/tests/gaussian_process/guide_performance_tools.h, contributions/MPI_IS_gaussian_process/tests/gaussian_process/math_tools_test.cpp, contributions/MPI_IS_gaussian_process/tools/math_tools.cpp, contributions/MPI_IS_gaussian_process/tools/math_tools.h
no functional changes -- clang-format changes only
=> enable clang-format for gaussian_proces source files

CMakeLists.txt, thirdparty/thirdparty.cmake
Replace `set(list ${list} value...)` with `list(APPEND list value...)`.
=> build system: cmake code simplification

locale/cs_CZ/messages.po
=> updates messages.po

src/myframe_events.cpp
fix a couple spelling errors in code comments
=> fix a couple spelling errors in code comments

src/myframe.cpp
apply some formatting changes from clang-format
=> apply some formatting changes from clang-format

src/camera.cpp, src/camera.h
GuideCamera member variables and methods to support ROI limiting
Add the member variables and methods to support ROI limiting.
Individual cameras implementing the capability will come in following PRs.
=> GuideCamera member variables and methods to support ROI limiting

src/guider_multistar.cpp
minor clenaup - spelling fixes in code comments
=> minor clenaup - spelling fixes in code comments
